name: Trigger AWS CodeBuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # AWS CodeBuild を実行
      - name: Run CodeBuild
        uses: neovasili/aws-codebuild@v1.1.1
        with:
          project-name: takeshi-y-build    # ← 実際の CodeBuild プロジェクト名に変更
          region: ap-northeast-1
          wait-for-completion: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

