version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Starting build..."

  build:
    commands:
      - echo "Running main.py..."
      - python main.py

artifacts:
  files:
    - '**/*'

