version: 0.2

env:
  variables:
    PYTHON_VERSION: "3.9"

phases:
  install:
    runtime-versions:
      python: $PYTHON_VERSION
    commands:
      - echo "アップグレード pip..."
      - pip install --upgrade pip
      - echo "依存関係インストール..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "CodeBuild の pre_build フェーズ開始..."

  build:
    commands:
      - echo "combine_data を単独実行..."
      - export RUN_COMBINE_ONLY=1
      - python takeshi.py

  post_build:
    commands:
      - echo "CodeBuild の post_build フェーズ完了"

artifacts:
  files:
    - combined_data.json

