name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # AWSリージョンを自分の環境に合わせてください

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: your-eb-application-name   # Elastic Beanstalkのアプリ名に置き換えてください
          environment_name: your-eb-environment-name   # Elastic Beanstalkの環境名に置き換えてください
          version_label: ${{ github.sha }}
          region: us-east-1                             # 同じくリージョンを合わせてください
          bucket_name: your-s3-bucket-name             # アプリのZIPを置くS3バケット名に置き換えてください
          bucket_key: your-app.zip                       # S3にアップロードするZIPファイル名

